"""Increase short_code length to 16

Revision ID: 911ccd146642
Revises: 2bb3ec5cd21d
Create Date: 2026-04-21 13:56:56.643716

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "911ccd146642"
down_revision = "2bb3ec5cd21d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("url_mappings", schema=None) as batch_op:
        batch_op.alter_column(
            "short_code",
            existing_type=sa.VARCHAR(length=8),
            type_=sa.String(length=16),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("url_mappings", schema=None) as batch_op:
        batch_op.alter_column(
            "short_code",
            existing_type=sa.String(length=16),
            type_=sa.VARCHAR(length=8),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
